Repository sqlancer/sqlancer, pull requests merged in 2020-07, with the labels that each got.

#85 [ClickHouse] implement GROUP BY TLP Oracle.
  src/sqlancer/ComparatorHelper.java
  src/sqlancer/clickhouse/ClickHouseErrors.java
  src/sqlancer/clickhouse/ClickHouseOptions.java
  src/sqlancer/clickhouse/oracle/tlp/ClickHouseTLPGroupByOracle.java
  src/sqlancer/clickhouse/oracle/tlp/ClickHouseTLPHavingOracle.java
  test/sqlancer/dbms/TestClickHouse.java
Labels: ClickHouse

#88 Enhance the Query class
  src/sqlancer/ComparatorHelper.java
  src/sqlancer/Main.java
  src/sqlancer/Query.java
  src/sqlancer/QueryAdapter.java
  src/sqlancer/QueryResultCheckAdapter.java
  src/sqlancer/clickhouse/oracle/tlp/ClickHouseTLPGroupByOracle.java
  src/sqlancer/clickhouse/oracle/tlp/ClickHouseTLPHavingOracle.java
  src/sqlancer/clickhouse/oracle/tlp/ClickHouseTLPWhereOracle.java
  src/sqlancer/cockroachdb/oracle/CockroachDBNoRECOracle.java
  src/sqlancer/cockroachdb/oracle/tlp/CockroachDBTLPAggregateOracle.java
  src/sqlancer/cockroachdb/oracle/tlp/CockroachDBTLPDistinctOracle.java
  src/sqlancer/cockroachdb/oracle/tlp/CockroachDBTLPExtendedWhereOracle.java
  src/sqlancer/cockroachdb/oracle/tlp/CockroachDBTLPGroupByOracle.java
  src/sqlancer/cockroachdb/oracle/tlp/CockroachDBTLPHavingOracle.java
  src/sqlancer/cockroachdb/oracle/tlp/CockroachDBTLPJoinOracle.java
  src/sqlancer/cockroachdb/oracle/tlp/CockroachDBTLPWhereOracle.java
  src/sqlancer/duckdb/test/DuckDBNoRECOracle.java
  src/sqlancer/duckdb/test/DuckDBQueryPartitioningAggregateTester.java
  src/sqlancer/duckdb/test/DuckDBQueryPartitioningDistinctTester.java
  src/sqlancer/duckdb/test/DuckDBQueryPartitioningGroupByTester.java
  src/sqlancer/duckdb/test/DuckDBQueryPartitioningHavingTester.java
  src/sqlancer/duckdb/test/DuckDBQueryPartitioningWhereTester.java
  src/sqlancer/mariadb/MariaDBProvider.java
  src/sqlancer/mariadb/oracle/MariaDBNoRECOracle.java
  src/sqlancer/mysql/oracle/MySQLTLPWhereOracle.java
  src/sqlancer/postgres/PostgresProvider.java
  src/sqlancer/postgres/gen/PostgresQueryCatalogGenerator.java
  src/sqlancer/postgres/oracle/PostgresNoRECOracle.java
  src/sqlancer/postgres/oracle/tlp/PostgresTLPAggregateOracle.java
  src/sqlancer/postgres/oracle/tlp/PostgresTLPHavingOracle.java
  src/sqlancer/postgres/oracle/tlp/PostgresTLPWhereOracle.java
  src/sqlancer/sqlite3/SQLite3Helper.java
  src/sqlancer/sqlite3/SQLite3Provider.java
  src/sqlancer/sqlite3/oracle/SQLite3NoRECOracle.java
  src/sqlancer/sqlite3/oracle/SQLite3PivotedQuerySynthesisOracle.java
  src/sqlancer/sqlite3/oracle/tlp/SQLite3TLPAggregateOracle.java
  src/sqlancer/sqlite3/oracle/tlp/SQLite3TLPDistinctOracle.java
  src/sqlancer/sqlite3/oracle/tlp/SQLite3TLPGroupByOracle.java
  src/sqlancer/sqlite3/oracle/tlp/SQLite3TLPHavingOracle.java
  src/sqlancer/sqlite3/oracle/tlp/SQLite3TLPWhereOracle.java
  src/sqlancer/sqlite3/schema/SQLite3Schema.java
  src/sqlancer/tidb/gen/TiDBAlterTableGenerator.java
  src/sqlancer/tidb/oracle/TiDBTLPHavingOracle.java
  src/sqlancer/tidb/oracle/TiDBTLPWhereOracle.java
Labels: enhancement

#93 Refactor the query logging and schema updating
  src/sqlancer/ComparatorHelper.java
  src/sqlancer/DatabaseProvider.java
  src/sqlancer/GlobalState.java
  src/sqlancer/Main.java
  src/sqlancer/ProviderAdapter.java
  src/sqlancer/Query.java
  src/sqlancer/QueryAdapter.java
  src/sqlancer/QueryResultCheckAdapter.java
  src/sqlancer/StatementExecutor.java
  src/sqlancer/clickhouse/ClickHouseProvider.java
  src/sqlancer/clickhouse/gen/ClickHouseTableGenerator.java
  src/sqlancer/cockroachdb/CockroachDBProvider.java
  src/sqlancer/cockroachdb/oracle/CockroachDBNoRECOracle.java
  src/sqlancer/duckdb/DuckDBProvider.java
  src/sqlancer/mariadb/MariaDBProvider.java
  src/sqlancer/mariadb/gen/MariaDBTableGenerator.java
  src/sqlancer/mysql/MySQLGlobalState.java
  src/sqlancer/mysql/MySQLProvider.java
  src/sqlancer/mysql/gen/MySQLTableGenerator.java
  src/sqlancer/postgres/PostgresGlobalState.java
  src/sqlancer/postgres/PostgresProvider.java
  src/sqlancer/postgres/gen/PostgresQueryCatalogGenerator.java
  src/sqlancer/sqlite3/SQLite3Provider.java
  src/sqlancer/sqlite3/gen/SQLite3CreateVirtualRtreeTabelGenerator.java
  src/sqlancer/sqlite3/gen/ddl/SQLite3CreateVirtualFTSTableGenerator.java
  src/sqlancer/sqlite3/gen/ddl/SQLite3TableGenerator.java
  src/sqlancer/tidb/TiDBProvider.java
Labels: enhancement

#96 Log the execution time of statements
  src/sqlancer/ExecutionTimer.java
  src/sqlancer/GlobalState.java
  src/sqlancer/Main.java
  src/sqlancer/MainOptions.java
Labels: enhancement

#99 Move common functionality from the individual testing implementations…
  src/sqlancer/ProviderAdapter.java
  src/sqlancer/clickhouse/ClickHouseProvider.java
  src/sqlancer/cockroachdb/CockroachDBProvider.java
  src/sqlancer/duckdb/DuckDBProvider.java
  src/sqlancer/mariadb/MariaDBProvider.java
  src/sqlancer/mariadb/oracle/MariaDBNoRECOracle.java
  src/sqlancer/mysql/MySQLProvider.java
  src/sqlancer/postgres/PostgresProvider.java
  src/sqlancer/sqlite3/SQLite3Provider.java
  src/sqlancer/tidb/TiDBProvider.java
Labels: enhancement

#100 [SQLite3] Use the statement executor
  src/sqlancer/sqlite3/SQLite3Provider.java
Labels: sqlite

#83 [ClickHouse] Add Travis CI check for ClickHouse
  .travis.yml
  codecov.yml
  src/sqlancer/clickhouse/ClickHouseErrors.java
  src/sqlancer/clickhouse/ClickHouseOptions.java
  src/sqlancer/clickhouse/ClickHouseProvider.java
  src/sqlancer/clickhouse/ClickHouseToStringVisitor.java
  src/sqlancer/clickhouse/ClickHouseVisitor.java
  src/sqlancer/clickhouse/ast/ClickHouseExpression.java
  src/sqlancer/clickhouse/gen/ClickHouseInsertGenerator.java
  src/sqlancer/clickhouse/gen/ClickHouseTableGenerator.java
  src/sqlancer/clickhouse/oracle/tlp/ClickHouseTLPAggregateOracle.java
  src/sqlancer/clickhouse/oracle/tlp/ClickHouseTLPDistinctOracle.java
  test/sqlancer/clickhouse/ast/ClickHouseBinaryComparisonOperationTest.java
  test/sqlancer/dbms/TestClickHouse.java
Labels: ClickHouse

#106 Add a method to specify whether it makes sense to retry getting a query from an action
  src/sqlancer/AbstractAction.java
  src/sqlancer/StatementExecutor.java
  src/sqlancer/sqlite3/SQLite3Provider.java
Labels: enhancement

#108 Add an ExpressionGenerator interface
  src/sqlancer/clickhouse/gen/ClickHouseExpressionGenerator.java
  src/sqlancer/cockroachdb/gen/CockroachDBExpressionGenerator.java
  src/sqlancer/duckdb/gen/DuckDBExpressionGenerator.java
  src/sqlancer/gen/ExpressionGenerator.java
  src/sqlancer/gen/TypedExpressionGenerator.java
  src/sqlancer/gen/UntypedExpressionGenerator.java
  src/sqlancer/mysql/gen/MySQLExpressionGenerator.java
  src/sqlancer/postgres/gen/PostgresExpressionGenerator.java
  src/sqlancer/sqlite3/gen/SQLite3ExpressionGenerator.java
  src/sqlancer/tidb/TiDBExpressionGenerator.java
Labels: enhancement

#110 [MySQL] Fix compiler warnings
  src/sqlancer/mysql/ast/MySQLComputableFunction.java
Labels: mysql

#104 standardizing logs & current logs across test oracles & within the PostgreSQL implementation
  src/sqlancer/ComparatorHelper.java
  src/sqlancer/StateToReproduce.java
  src/sqlancer/postgres/oracle/PostgresNoRECOracle.java
  src/sqlancer/postgres/oracle/PostgresPivotedQuerySynthesisOracle.java
  src/sqlancer/postgres/oracle/tlp/PostgresTLPAggregateOracle.java
  src/sqlancer/postgres/oracle/tlp/PostgresTLPBase.java
Labels: enhancement

#116 Explain the expression generation mechanism
  docs/DEVELOPMENT.md
Labels: documentation

#118 Add some guidelines for commit messages and history
  docs/DEVELOPMENT.md
Labels: documentation

#117 Fix a link in the docs
  README.md
Labels: documentation

#133 Add option to specify connection URL
  src/sqlancer/postgres/PostgresOptions.java
  src/sqlancer/postgres/PostgresProvider.java
Labels: postgres

#136 Check for null second result in PostgresTLPAggregateOracle
  src/sqlancer/postgres/oracle/tlp/PostgresTLPAggregateOracle.java
Labels: postgres
